####################
###PLUGIN UPDATES###
####################

#Should this plugin update automatticly?
##false = No
##manual = You get a message for the plugin to update
##true = The plugin is automatticly updating
update: true
#What update stream should EasyPerms run of?
##dev = Development builds (not reccomended)
##beta = Beta builds
##rec = Reccomended builds (reccomended)
update-stream: rec

###################
###ON FIRST JOIN###
###################

#What group should the user be placed in? Case sensitive
##TIP: Type 0 for the user to be in no group. If you delete any user from a "user.yml" file, the user would be detected as default at next login.
default-group: Builder

###############
###ANTIGREIF###
###############

#Should logging be enabled?
##WARNING: If this isn't enabled, only the allow building, ussage and breaking feature of the antigreif part in EasyPerms will work!
##TIP: EasyPerms will not log players with "easyperms.ag.nologging"
ag-enabled: false

#Should rollback be allowed?
ag-allow-rollback: true


#############################
###ONLY FOR ADVANCED USERS###
#############################

#What language should EasyPerms use?
##en = English (reccomended)
##auto = Auto detects server country (Not reccomended for non-local hosting)
##TIP: Other languages than english can be translated incorrectly!
##TIP: Only international letters available!
language: en