#Chat format. Use {name} for the player name, {msg} for message, {world} for world name, {time} for time, {date} for date and {day} for day of the week (eg. Monday)
chat-format: '[&4Admin&f] &c{name}&f {msg}'
#Should this group be able to build
build: true
